/**
 * Client-side Algorand wallet helpers for the x402 premium gate.
 *
 * Heavily-dynamic imports keep algosdk + wallet SDKs out of the main bundle —
 * they only load when a user actually opens the payment gate.
 */

export type WalletKind = "pera" | "defly" | "manual";

export interface X402ClientConfig {
  network: "testnet" | "mainnet";
  genesisID: string;
  algodUrl: string;
  indexerUrl: string;
  receiverAddress: string;
  amountAlgo: number;
  amountMicro: number;
  assetId: number;
  explorerBase: string;
}

/** Connect the Pera wallet (mobile / extension via WalletConnect v2). */
export async function connectPera(): Promise<string> {
  const { PeraWalletConnect } = await import("@perawallet/connect");
  const pera = new PeraWalletConnect();
  const accounts = await pera.connect();
  if (!accounts?.[0]) throw new Error("No account selected in Pera.");
  return accounts[0];
}

/** Connect the Defly wallet (mobile / extension). */
export async function connectDefly(): Promise<string> {
  const { DeflyWalletConnect } = await import("@blockshake/defly-connect");
  const defly = new DeflyWalletConnect();
  const accounts = await defly.connect();
  if (!accounts?.[0]) throw new Error("No account selected in Defly.");
  return accounts[0];
}

/** Build a native ALGO payment transaction (unsigned, algosdk Transaction). */
async function buildPaymentTxn(opts: {
  from: string;
  to: string;
  amountMicro: number;
  note: string;
  algodUrl: string;
}) {
  const algosdk = await import("algosdk");
  const algod = new algosdk.Algodv2("", opts.algodUrl);
  const suggestedParams = await algod.getTransactionParams().do();
  return algosdk.makePaymentTxnWithSuggestedParamsFromObject({
    sender: opts.from,
    receiver: opts.to,
    amount: opts.amountMicro,
    note: new TextEncoder().encode(opts.note.slice(0, 500)),
    suggestedParams,
  });
}

/**
 * Sign + submit a payment using the connected wallet. Returns the on-chain
 * transaction id, which the server then verifies via the indexer.
 */
export async function payWithWallet(opts: {
  kind: WalletKind;
  walletAddress: string;
  to: string;
  amountMicro: number;
  note: string;
  algodUrl: string;
}): Promise<{ txId: string }> {
  if (opts.kind === "manual") {
    throw new Error("Manual mode: paste an existing transaction hash to verify.");
  }

  const txn = await buildPaymentTxn({
    from: opts.walletAddress,
    to: opts.to,
    amountMicro: opts.amountMicro,
    note: opts.note,
    algodUrl: opts.algodUrl,
  });

  if (opts.kind === "pera") {
    const { PeraWalletConnect } = await import("@perawallet/connect");
    const pera = new PeraWalletConnect();
    const signed = await pera.signTransaction([[{ txn, signers: [opts.walletAddress] }]]);
    const blob = signed?.[0];
    if (!blob) throw new Error("Pera returned no signed transaction.");
    const algosdk = await import("algosdk");
    const algod = new algosdk.Algodv2("", opts.algodUrl);
    const { txid } = await algod.sendRawTransaction(blob).do();
    return { txId: txid };
  }

  // Defly
  const { DeflyWalletConnect } = await import("@blockshake/defly-connect");
  const defly = new DeflyWalletConnect();
  const signed = await defly.signTransaction([[{ txn, signers: [opts.walletAddress] }]]);
  const blob = signed?.[0];
  if (!blob) throw new Error("Defly returned no signed transaction.");
  const algosdk = await import("algosdk");
  const algod = new algosdk.Algodv2("", opts.algodUrl);
  const { txid } = await algod.sendRawTransaction(blob).do();
  return { txId: txid };
}

/** Explorer link for a transaction on the configured network. */
export function explorerUrl(base: string, txId: string): string {
  return `${base}/tx/${txId}`;
}

/** Explorer link for an asset. */
export function assetExplorerUrl(base: string, assetId: number): string {
  return `${base}/asset/${assetId}`;
}

/* ------------------------------------------------------------------ */
/* ARC-3 NFT minting                                                   */
/* ------------------------------------------------------------------ */

export interface Arc3Metadata {
  name: string;
  description: string;
  image: string;
  external_url: string;
  properties: Record<string, string | number>;
}

/** Build the ARC-3 metadata JSON for a pitch deck NFT. */
export function buildArc3Metadata(opts: {
  title: string;
  tagline: string;
  creator: string;
  shareCode: string;
  origin: string;
  sections: { key: string; title: string }[];
}): Arc3Metadata {
  return {
    name: opts.title,
    description: `${opts.tagline}\n\nGenerated by Deckify AI — an investor-ready pitch deck forged from your repository docs.`,
    image: `${opts.origin}/api/og?deck=${opts.shareCode}`,
    external_url: `${opts.origin}/d/${opts.shareCode}`,
    properties: {
      Creator: opts.creator || "Anonymous",
      Sections: opts.sections.length,
      Slides: 13,
      "Generated by": "Deckify AI",
      ...Object.fromEntries(opts.sections.map((s, i) => [`Slide ${i + 1}`, s.title])),
    },
  };
}

/** SHA-256 hash of a string → 32-byte Uint8Array (Web Crypto API). */
async function sha256Bytes(input: string): Promise<Uint8Array> {
  const data = new TextEncoder().encode(input);
  const hash = await crypto.subtle.digest("SHA-256", data);
  return new Uint8Array(hash);
}

/** Mint a pitch deck as an ARC-3 NFT on Algorand. Returns asset ID + tx hash. */
export async function mintDeckNft(opts: {
  kind: Exclude<WalletKind, "manual">;
  walletAddress: string;
  metadata: Arc3Metadata;
  algodUrl: string;
}): Promise<{ assetId: number; txHash: string; metadataUrl: string }> {
  const algosdk = await import("algosdk");
  const algod = new algosdk.Algodv2("", opts.algodUrl);
  const suggestedParams = await algod.getTransactionParams().do();

  // 1. Serialize metadata JSON and compute SHA-256 hash
  const jsonStr = JSON.stringify(opts.metadata, null, 2);
  const metadataHash = await sha256Bytes(jsonStr);
  const metadataDataUri = `data:application/json;base64,${btoa(jsonStr)}`;

  // 2. Build asset creation transaction (ARC-3 NFT)
  const truncate = (s: string, max: number) =>
    s.length > max ? s.slice(0, max) : s;

  const txn = algosdk.makeAssetCreateTxnWithSuggestedParamsFromObject({
    sender: opts.walletAddress,
    total: 1n, // 1 of 1 — true NFT
    decimals: 0,
    defaultFrozen: false,
    manager: opts.walletAddress,
    reserve: opts.walletAddress,
    freeze: undefined,
    clawback: undefined,
    assetName: truncate(opts.metadata.name, 32),
    unitName: "PITCH",
    assetURL: truncate(metadataDataUri, 96), // data URI truncated if needed
    assetMetadataHash: metadataHash,
    note: new TextEncoder().encode("Deckify AI — ARC-3 NFT mint"),
    suggestedParams,
  });

  // 3. Sign + submit via the connected wallet
  if (opts.kind === "pera") {
    const { PeraWalletConnect } = await import("@perawallet/connect");
    const pera = new PeraWalletConnect();
    const signed = await pera.signTransaction([[{ txn, signers: [opts.walletAddress] }]]);
    const blob = signed?.[0];
    if (!blob) throw new Error("Pera returned no signed transaction.");
    const { txid } = await algod.sendRawTransaction(blob).do();
    // Wait for confirmation to get the asset ID
    const result = await algosdk.waitForConfirmation(algod, txid, 4);
    const assetId = Number(result.assetIndex ?? 0);
    return { assetId, txHash: txid, metadataUrl: metadataDataUri };
  }

  // Defly
  const { DeflyWalletConnect } = await import("@blockshake/defly-connect");
  const defly = new DeflyWalletConnect();
  const signed = await defly.signTransaction([[{ txn, signers: [opts.walletAddress] }]]);
  const blob = signed?.[0];
  if (!blob) throw new Error("Defly returned no signed transaction.");
  const { txid } = await algod.sendRawTransaction(blob).do();
  const result = await algosdk.waitForConfirmation(algod, txid, 4);
  const assetId = Number(result.assetIndex ?? 0);
  return { assetId, txHash: txid, metadataUrl: metadataDataUri };
}
