/**
 * ⭐ x402 Demo Server — Main entry point
 *
 * This is a payment-protected API server using the x402 HTTP protocol.
 * DO NOT EDIT this file unless you know what you're doing.
 *
 * The x402 flow:
 * 1. Client makes request
 * 2. Server responds with 402 Payment Required + payment details
 * 3. Client signs transaction with wallet
 * 4. Client retries with payment signature
 * 5. Server validates payment and returns data
 */

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { serve } from '@hono/node-server';
import dotenv from 'dotenv';
import algosdk from 'algosdk';

import { getPaymentConfig, getAvmAddress } from './endpoints.config.js';
import { handleWeatherRequest } from './handlers/weather.js';
import { handleAnalyticsRequest } from './handlers/analytics.js';
import { handleAiAnalysisRequest } from './handlers/ai-analysis.js';
import { handleCreatorContentRequest } from './handlers/creator-content.js';

dotenv.config();

const app = new Hono();
const PORT = parseInt(process.env.PORT || '4021', 10);

// CORS middleware
app.use('*', cors({
  origin: '*',
  allowMethods: ['GET', 'POST', 'OPTIONS'],
  allowHeaders: ['Content-Type', 'Payment-Signature', 'X-Payment'],
}));

// Health check
app.get('/', (c) => {
  return c.json({
    name: 'Deckify AI x402 API Server',
    version: '1.0.0',
    status: 'running',
    network: process.env.AVM_NETWORK || 'testnet',
    address: getAvmAddress(),
    endpoints: Object.keys(getPaymentConfig()),
  });
});

/**
 * x402 Payment Middleware
 *
 * Intercepts requests to payment-protected endpoints.
 * If no valid payment is provided, returns 402 with payment details.
 */
async function x402Middleware(endpoint: string, c: any) {
  const config = getPaymentConfig();
  const paymentConfig = config[endpoint as keyof typeof config];

  if (!paymentConfig) {
    return null; // No payment required for this endpoint
  }

  // Check for payment header
  const paymentHeader = c.req.header('Payment-Signature') || c.req.header('X-Payment');

  if (!paymentHeader) {
    // Return 402 Payment Required
    return c.json({
      error: 'Payment Required',
      message: `This endpoint requires a payment of ${paymentConfig.accepts[0].price} USDC`,
      payment: {
        amount: paymentConfig.accepts[0].price,
        network: 'algorand-testnet',
        receiver: getAvmAddress(),
        description: paymentConfig.description,
      },
    }, 402);
  }

  // Verify payment (simplified - in production, verify on-chain)
  try {
    const paymentData = JSON.parse(paymentHeader);

    // For demo purposes, we trust the payment signature
    // In production, you would verify the transaction on-chain using the Algorand indexer
    console.log(`✓ PAYMENT VERIFIED - ${endpoint} - Amount: ${paymentConfig.accepts[0].price} USDC`);

    return null; // Payment verified, continue to handler
  } catch (error) {
    return c.json({
      error: 'Invalid Payment',
      message: 'The provided payment signature is invalid',
    }, 400);
  }
}

// Register payment-protected endpoints
app.get('/weather', async (c) => {
  const middlewareResult = await x402Middleware('GET /weather', c);
  if (middlewareResult) return middlewareResult;
  return handleWeatherRequest(c);
});

app.get('/analytics', async (c) => {
  const middlewareResult = await x402Middleware('GET /analytics', c);
  if (middlewareResult) return middlewareResult;
  return handleAnalyticsRequest(c);
});

app.post('/ai-analysis', async (c) => {
  const middlewareResult = await x402Middleware('POST /ai-analysis', c);
  if (middlewareResult) return middlewareResult;
  return handleAiAnalysisRequest(c);
});

app.get('/creator-content/:id', async (c) => {
  const middlewareResult = await x402Middleware('GET /creator-content/:id', c);
  if (middlewareResult) return middlewareResult;
  return handleCreatorContentRequest(c);
});

// 404 handler
app.notFound((c) => {
  return c.json({
    error: 'Not Found',
    message: 'The requested endpoint does not exist',
    availableEndpoints: Object.keys(getPaymentConfig()),
  }, 404);
});

// Error handler
app.onError((err, c) => {
  console.error('Server Error:', err);
  return c.json({
    error: 'Internal Server Error',
    message: err.message,
  }, 500);
});

// Start server
console.log(`
🚀 Deckify AI x402 API Server
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Port: ${PORT}
Network: ${process.env.AVM_NETWORK || 'testnet'}
Address: ${getAvmAddress()}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Endpoints:
${Object.keys(getPaymentConfig()).map(ep => `  ${ep}`).join('\n')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);

serve({
  fetch: app.fetch,
  port: PORT,
});

export default app;
